# Automatically generated by: ros2nix --flake --distro humble
{ nix-ros-overlay ? builtins.fetchTarball
  "https://github.com/lopsided98/nix-ros-overlay/archive/master.tar.gz"
, pkgs ? import nix-ros-overlay { }, rosDistro ? "humble", extraPkgs ? { }
, extraPaths ? [ ], withPackages ? _: [ ], extraShellHook ? "", }:
pkgs.mkShell {
  name = "ros2nix ${rosDistro} shell";
  packages = [
    (pkgs.rosPackages.${rosDistro}.buildEnv {
      wrapPrograms = false;
      paths = [
        pkgs.colcon
        pkgs.rosPackages.${rosDistro}.ros-core

        # Work around https://github.com/lopsided98/nix-ros-overlay/pull/624
        pkgs.rosPackages.${rosDistro}.ament-cmake-core
        pkgs.rosPackages.${rosDistro}.python-cmake-module
      ] ++ (with pkgs;
        with pkgs.rosPackages.${rosDistro};
        with extraPkgs; [
          # Dependencies from package.xml files
          ament-cmake
          ament-copyright
          ament-flake8
          ament-lint-auto
          ament-lint-common
          ament-pep257
          cv-bridge
          python312Packages.ultralytics
          python312Packages.torch
          python312Packages.opencv4
          python3Packages.pytest
          rclpy
          robot-localization
          std-msgs
        ]) ++ builtins.attrValues extraPkgs ++ extraPaths
        ++ withPackages (pkgs // pkgs.rosPackages.${rosDistro});
    })
  ];
  shellHook = ''
    # Setup ROS 2 shell completion. Doing it in direnv is useless.
    if [[ ! $DIRENV_IN_ENVRC ]]; then
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete ros2)"
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete colcon)"
    fi
  '' + extraShellHook;
}
