realsense2_camera_node:
  ros__parameters:
    depth_module.depth_profile: "640x480x30"
    rgb_camera.color_profile: "640x480x30"
    enable_color: true
    enable_gyro: true
    enable_accel: true
    enable_rgbd: true
    enable_sync: true
    align_depth.enable: true
    unite_imu_method: "linear_interpolation"
