# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, astra-msgs, cv-bridge, opencv-python, python3-ultralytics, python3Packages, rclpy, std-msgs }:
buildRosPackage rec {
  pname = "ros-humble-macula-pkg";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 python3Packages.pytest ];
  propagatedBuildInputs = [ astra-msgs cv-bridge opencv-python python3-ultralytics rclpy std-msgs ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
