# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, astra-msgs, builtin-interfaces, geometry-msgs, nav2-msgs, python3Packages, rclpy, std-msgs }:
buildRosPackage rec {
  pname = "ros-humble-clucky-control";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 python3Packages.pytest ];
  propagatedBuildInputs = [ astra-msgs builtin-interfaces geometry-msgs nav2-msgs rclpy std-msgs ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
