# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, astra-msgs, image-transport, joint-state-publisher, joint-state-publisher-gui, nav-msgs, rclcpp, rclcpp-action, realsense2-camera, robot-state-publisher, rviz, std-msgs, xacro }:
buildRosPackage rec {
  pname = "ros-humble-actions-cpp";
  version = "0.1.1";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ astra-msgs image-transport joint-state-publisher joint-state-publisher-gui nav-msgs rclcpp rclcpp-action realsense2-camera robot-state-publisher rviz std-msgs xacro ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
